package Comprog2;

/**
 * Finals Output on Computer Programming 2
 * @author John Paolo Rosales
 *  I did not use button group, and do it differently from my midterm output to explore different ways I can utilize radio buttons.
 */
public class Pizza_Shop extends javax.swing.JFrame {

    /**
     * Creates new form Pizza_Shop
     */
    public Pizza_Shop() {
        initComponents();
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblPizzaTopping = new javax.swing.JLabel();
        LblPizzaSize = new javax.swing.JLabel();
        LblPizzaType = new javax.swing.JLabel();
        buttonConfirm = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        panelToppings = new javax.swing.JPanel();
        cbTomato = new javax.swing.JCheckBox();
        cbGreenPepper = new javax.swing.JCheckBox();
        cbBlackOlives = new javax.swing.JCheckBox();
        cbMushrooms = new javax.swing.JCheckBox();
        cbExtraCheese = new javax.swing.JCheckBox();
        cbPepperoni = new javax.swing.JCheckBox();
        cbSausage = new javax.swing.JCheckBox();
        panelSize = new javax.swing.JPanel();
        radSmall = new javax.swing.JRadioButton();
        radMedium = new javax.swing.JRadioButton();
        radLarge = new javax.swing.JRadioButton();
        panelType = new javax.swing.JPanel();
        radThinCrust = new javax.swing.JRadioButton();
        radMediumCrust = new javax.swing.JRadioButton();
        radPan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOutput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblPizzaTopping.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblPizzaTopping.setText("Each Topping $1.50");
        getContentPane().add(LblPizzaTopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 181, -1));

        LblPizzaSize.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblPizzaSize.setText("Pizza Size");
        getContentPane().add(LblPizzaSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 106, -1));

        LblPizzaType.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LblPizzaType.setText("Pizza Type");
        getContentPane().add(LblPizzaType, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 100, -1));

        buttonConfirm.setBackground(new java.awt.Color(0, 51, 153));
        buttonConfirm.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        buttonConfirm.setText("Confirm Selection");
        buttonConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(buttonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 230, 59));

        buttonClear.setBackground(new java.awt.Color(153, 0, 0));
        buttonClear.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        buttonClear.setText("Clear Selection");
        buttonClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        getContentPane().add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 260, 205, 59));

        panelToppings.setBackground(new java.awt.Color(255, 255, 255));
        panelToppings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbTomato.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbTomato.setText("Tomato");

        cbGreenPepper.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbGreenPepper.setText("Green Pepper");
        cbGreenPepper.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbGreenPepper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGreenPepperActionPerformed(evt);
            }
        });

        cbBlackOlives.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbBlackOlives.setText("Black Olives");
        cbBlackOlives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBlackOlivesActionPerformed(evt);
            }
        });

        cbMushrooms.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbMushrooms.setText("Mushrooms");
        cbMushrooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMushroomsActionPerformed(evt);
            }
        });

        cbExtraCheese.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbExtraCheese.setText("Extra Cheese");

        cbPepperoni.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbPepperoni.setText("Pepperoni");

        cbSausage.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cbSausage.setText("Sausage");

        javax.swing.GroupLayout panelToppingsLayout = new javax.swing.GroupLayout(panelToppings);
        panelToppings.setLayout(panelToppingsLayout);
        panelToppingsLayout.setHorizontalGroup(
            panelToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToppingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbGreenPepper, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(cbBlackOlives, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelToppingsLayout.createSequentialGroup()
                        .addGroup(panelToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTomato, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbExtraCheese)
                            .addComponent(cbPepperoni, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSausage, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMushrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelToppingsLayout.setVerticalGroup(
            panelToppingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToppingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTomato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGreenPepper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBlackOlives)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMushrooms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbExtraCheese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPepperoni, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSausage)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(panelToppings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        panelSize.setBackground(new java.awt.Color(255, 255, 255));
        panelSize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        radSmall.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        radSmall.setText("Small: $6.50");
        radSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSmallActionPerformed(evt);
            }
        });

        radMedium.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        radMedium.setText("Medium $8.50");
        radMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMediumActionPerformed(evt);
            }
        });

        radLarge.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        radLarge.setText("Large $10.00");
        radLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSizeLayout = new javax.swing.GroupLayout(panelSize);
        panelSize.setLayout(panelSizeLayout);
        panelSizeLayout.setHorizontalGroup(
            panelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSizeLayout.createSequentialGroup()
                .addComponent(radLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelSizeLayout.createSequentialGroup()
                .addGroup(panelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radMedium, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addGroup(panelSizeLayout.createSequentialGroup()
                        .addComponent(radSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSizeLayout.setVerticalGroup(
            panelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSizeLayout.createSequentialGroup()
                .addComponent(radSmall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(radMedium)
                .addGap(18, 18, 18)
                .addComponent(radLarge))
        );

        getContentPane().add(panelSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, 102));

        panelType.setBackground(new java.awt.Color(255, 255, 255));
        panelType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        radThinCrust.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        radThinCrust.setText("Thin Crust");
        radThinCrust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radThinCrustActionPerformed(evt);
            }
        });

        radMediumCrust.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        radMediumCrust.setText("Medium Crust");
        radMediumCrust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMediumCrustActionPerformed(evt);
            }
        });

        radPan.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        radPan.setText("Pan");
        radPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTypeLayout = new javax.swing.GroupLayout(panelType);
        panelType.setLayout(panelTypeLayout);
        panelTypeLayout.setHorizontalGroup(
            panelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTypeLayout.createSequentialGroup()
                .addGroup(panelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radPan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radThinCrust, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radMediumCrust))
                .addGap(0, 7, Short.MAX_VALUE))
        );
        panelTypeLayout.setVerticalGroup(
            panelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTypeLayout.createSequentialGroup()
                .addComponent(radThinCrust)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(radMediumCrust)
                .addGap(18, 18, 18)
                .addComponent(radPan))
        );

        getContentPane().add(panelType, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jOutput.setBackground(new java.awt.Color(255, 255, 153));
        jOutput.setColumns(20);
        jOutput.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jOutput.setRows(5);
        jOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jOutput);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 630, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Comprog2/PizzaShopBG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGreenPepperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGreenPepperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGreenPepperActionPerformed

    private void cbBlackOlivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBlackOlivesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBlackOlivesActionPerformed

    private void cbMushroomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMushroomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMushroomsActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        
        // Check Box (Toppings)
        cbTomato.setSelected(false);
        cbGreenPepper.setSelected(false);
        cbBlackOlives.setSelected(false);
        cbMushrooms.setSelected(false);
        cbExtraCheese.setSelected(false);
        cbPepperoni.setSelected(false);
        cbSausage.setSelected(false);
        
        // Radio Buttons (Size)
        radSmall.setSelected(false);
        radMedium.setSelected(false);
        radLarge.setSelected(false);
        
        // Radio Buttons (Type)
        radThinCrust.setSelected(false);
        radMediumCrust.setSelected(false);
        radPan.setSelected(false);
        
       jOutput.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmActionPerformed

        
// Strings and Doubles
        
        String Type ="";
        String Size ="";
        String Toppings="";
        
        double Total = 0;
      
      
// If Else Statements on Pizza Sizes Computation
        if (radSmall.isSelected()){
            Total = Total + 6.50 ;
        }
            else if (radMedium.isSelected()){
                Total= Total + 8.50 ;
            }

            else if (radLarge.isSelected()){
                Total= Total + 10.00 ;
            }
        
//If Else Statements on Pizza Toppings
        if (cbTomato.isSelected()){
            Total = Total + 1.50;
        }
        
        if (cbGreenPepper.isSelected()){
            Total = Total + 1.50;
        }
        
        if (cbBlackOlives.isSelected()){
            Total = Total + 1.50;
        }
        
        if (cbMushrooms.isSelected()){
            Total = Total + 1.50;
        }
        
        if (cbExtraCheese.isSelected()){
            Total = Total + 1.50;
        }
        
        if (cbPepperoni.isSelected()){
            Total = Total + 1.50;
        }
        
        if (cbSausage.isSelected()){
            Total = Total + 1.50;
        }

// Output on Pizza Size
        
        if (radSmall.isSelected()){
            Type = "Small" ;
        }
        
            else if (radMedium.isSelected()){
                Type = "Medium" ;  
            }

            else if (radLarge.isSelected()){
                Type = "Large" ;  
            }

//  Output on Pizza Type
        if (radThinCrust.isSelected()){
            Size = "Thin Crust" ;
        }
        
        else if (radMediumCrust.isSelected()){
            Size = "Medium Crust" ;
        }
        
        else if (radPan.isSelected()){
            Size = "Pan" ;
        }
// Output on Pizza Toppings

        if (cbTomato.isSelected()){
            Toppings = Toppings + cbTomato.getText() + ", ";
        }
        
        if (cbGreenPepper.isSelected()){
            Toppings = Toppings + cbGreenPepper.getText() + ", ";
        }
        
        if (cbBlackOlives.isSelected()){
            Toppings = Toppings + cbBlackOlives.getText() + ", ";
        }
        
        if (cbMushrooms.isSelected()){
            Toppings = Toppings + cbMushrooms.getText() + ", ";
        }
        
        if (cbExtraCheese.isSelected()){
            Toppings = Toppings + cbExtraCheese.getText() + ", ";
        }
        
        if (cbPepperoni.isSelected()){
            Toppings = Toppings + cbPepperoni.getText() + ", ";
        }
        
        if (cbSausage.isSelected()){
            Toppings = Toppings + cbSausage.getText() + ", ";
        }


//Output
        jOutput.setText("Cashier Name: John Paolo Rosales");
        jOutput.append("\nPizza Size: " + Size);
        jOutput.append("\nPizza Type: " + Type);
        jOutput.append("\nPizza Toppings: " + Toppings);
        jOutput.append("\nTotal: $ " + Total);


        
        jOutput.setEditable(false);
        
            
    }//GEN-LAST:event_buttonConfirmActionPerformed

    private void radSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSmallActionPerformed
        if (radSmall.isSelected())
            radMedium.setSelected(false);
            radLarge.setSelected(false);
    }//GEN-LAST:event_radSmallActionPerformed

    private void radMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMediumActionPerformed
        if (radMedium.isSelected())
            radSmall.setSelected(false);
            radLarge.setSelected(false);
    }//GEN-LAST:event_radMediumActionPerformed

    private void radLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLargeActionPerformed
        if (radLarge.isSelected())
            radSmall.setSelected(false);
            radMedium.setSelected(false);
    }//GEN-LAST:event_radLargeActionPerformed

    private void radThinCrustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radThinCrustActionPerformed
        if (radThinCrust.isSelected())
            radMediumCrust.setSelected(false);
            radPan.setSelected(false);
    }//GEN-LAST:event_radThinCrustActionPerformed

    private void radMediumCrustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMediumCrustActionPerformed
        if (radMediumCrust.isSelected())
            radThinCrust.setSelected(false);
            radPan.setSelected(false);
    }//GEN-LAST:event_radMediumCrustActionPerformed

    private void radPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPanActionPerformed
        if (radPan.isSelected())
            radThinCrust.setSelected(false);
            radMediumCrust.setSelected(false);
    }//GEN-LAST:event_radPanActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza_Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza_Shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblPizzaSize;
    private javax.swing.JLabel LblPizzaTopping;
    private javax.swing.JLabel LblPizzaType;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.JCheckBox cbBlackOlives;
    private javax.swing.JCheckBox cbExtraCheese;
    private javax.swing.JCheckBox cbGreenPepper;
    private javax.swing.JCheckBox cbMushrooms;
    private javax.swing.JCheckBox cbPepperoni;
    private javax.swing.JCheckBox cbSausage;
    private javax.swing.JCheckBox cbTomato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jOutput;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelSize;
    private javax.swing.JPanel panelToppings;
    private javax.swing.JPanel panelType;
    private javax.swing.JRadioButton radLarge;
    private javax.swing.JRadioButton radMedium;
    private javax.swing.JRadioButton radMediumCrust;
    private javax.swing.JRadioButton radPan;
    private javax.swing.JRadioButton radSmall;
    private javax.swing.JRadioButton radThinCrust;
    // End of variables declaration//GEN-END:variables
}
